### ISSUE TITLE
New feed

### ISSUE THREAD

**Issue by cyb3rmik3** [Bert-JanP/Open-Source-Threat-Intel-Feeds#10]
Hey,

Maybe consider the following source for feeds:

https://osint.digitalside.it/

Some good txt files there.

M.

**Comment by Bert-JanP** [comment]
Thanks! Will dive into it later this week.

**Comment by Bert-JanP** [comment]
Additions will be pushed later this week, including KQL :). Thanks again for mentioning this source.
